env:
  browser: true
  es6: true
extends:
  - 'plugin:react/recommended'
  - airbnb
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 11
  sourceType: module
plugins:
  - react
rules:
  react/jsx-filename-extension:
    - 1
    - { extensions: ['.js', '.jsx'] }
  no-param-reassign:
    - 0
  no-unused-vars: 
    - 'off'
  max-len:
    - 'off' 
  react/jsx-props-no-spreading:
    - 'off'
  import/prefer-default-export:
    - 'off'
  jsx-a11y/anchor-is-valid:
    - 0
